version: "3.8"

services:
  database:
    container_name: scarlet_bot_mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: scarlet
      MYSQL_ROOT_PASSWORD: tmdcks2416@
    ports:
      - 3306:3306
  app:
    container_name: scarlet_bot_app
    build:
      context: /home/ssm-user/Scarlet-discord-bot
      dockerfile: /home/ssm-user/Scarlet-discord-bot/Dockerfile
    ports:
      - "9999:9999"
